version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: wallet_mysql57
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wallet
      MYSQL_PASSWORD: wallet
    ports:
      - "3307:3306"
    command: ["--sql_mode=", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uwallet", "-pwallet"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: wallet_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ["npm", "run", "start:dev"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
